ci: update flow

diff --git a/{{ cookiecutter.__project_name_dashed }}/.github/workflows/continuous_integration.yml b/{{ cookiecutter.__project_name_dashed }}/.github/workflows/continuous_integration.yml
--- a/{{ cookiecutter.__project_name_dashed }}/.github/workflows/continuous_integration.yml
+++ b/{{ cookiecutter.__project_name_dashed }}/.github/workflows/continuous_integration.yml
@@ -19,10 +19,10 @@ jobs:
     steps:
     - uses: actions/checkout@v3
 
-    - name: Set up Python 3.11
+    - name: Set up Python 3.12
       uses: actions/setup-python@v4
       with:
-        python-version: '3.11'
+        python-version: '3.12'
         cache: 'pip'
 
     - name: Install dependencies
@@ -34,13 +34,13 @@ jobs:
       uses: actions/cache@v3
       with:
         path: .tox
-        key: 3.11-tox-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('tox.ini') }}
+        key: 3.12-tox-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('tox.ini') }}
 
     - name: Cache pre-commit environment
       uses: actions/cache@v3
       with:
         path: ~/.cache/pre-commit
-        key: 3.11-pre-commit-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('.pre-commit-config.yaml') }}
+        key: 3.12-pre-commit-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('.pre-commit-config.yaml') }}
 
     - name: Lint and format with tox
       run: tox -e lint
@@ -56,7 +56,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        python-version: ['3.9', '3.10', '3.11']
+        python-version: ['3.10', '3.11', '3.12']
 
     steps:
     - uses: actions/checkout@v3
@@ -89,10 +89,10 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      - name: Set up Python 3.11
+      - name: Set up Python 3.12
         uses: actions/setup-python@v4
         with:
-          python-version: '3.11'
+          python-version: '3.12'
           cache: 'pip'
 
       - name: Install dependencies
@@ -123,35 +123,82 @@ jobs:
 
   release:
     runs-on: ubuntu-latest
-    needs: test  # Ensure tests pass before releasing
+    needs: 
+      - test  # Ensure tests pass before releasing
+      - docs  # Ensure docs are built before releasing to avoid unsynced docs
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0 # Fetch all history for changelog generation
 
-      - name: Set up Python 3.11
+      - name: Set up Python 3.12
         uses: actions/setup-python@v4
         with:
-          python-version: '3.11'
+          python-version: '3.12'
           cache: 'pip'
 
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           python -m pip install tox
+          python -m pip install poetry
+
+      - name: Configure git
+        run: |
+          git config user.name "${{ github.actor }}"
+          git config user.email "${{ github.actor }}@users.noreply.github.com"
+          echo "https://${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
+          
+      - name: Configure poetry
+        run: |
+          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
 
       - name: Determine version type from commit message
         id: get_version
         run: |
           echo "Commit message: ${{ github.event.head_commit.message }}"
           if [[ "${{ github.event.head_commit.message }}" == feat\!* ]]; then
-            echo "version_type=major" >> $GITHUB_ENV
+            echo "::set-output name=version_type::major"
+            echo "::set-output name=release_proceed::true"
           elif [[ "${{ github.event.head_commit.message }}" == feat:* ]]; then
-            echo "version_type=minor" >> $GITHUB_ENV
-          elif [[ "${{ github.event.head_commit.message }}" == fix:* ]]; then
-            echo "version_type=patch" >> $GITHUB_ENV
+            echo "::set-output name=version_type::minor"
+            echo "::set-output name=release_proceed::true"
+          elif [[ "${{ github.event.head_commit.message }}" == fix:* \
+              || "${{ github.event.head_commit.message }}" == refactor:* ]]; then
+            echo "::set-output name=version_type::patch"
+            echo "::set-output name=release_proceed::true"
           else
-            echo "version_type=minor" >> $GITHUB_ENV  # Default to minor if not specified
+            echo "::set-output name=release_proceed::false"  # No release needed
           fi
 
       - name: Run release with tox
+        if: steps.get_version.outputs.release_proceed == 'true'
         run: |
-          tox -e release -- ${{ env.version_type }}
+          chmod +x scripts/release.sh
+          max_attempts=3
+          attempt=0
+          until [ $attempt -ge $max_attempts ]
+          do
+            tox -e release -- ${{ steps.get_version.outputs.version_type }} && break
+            exit_code=$?
+
+            if [ $exit_code -eq 0 ]; then
+              break  # Success
+            elif [ $exit_code -eq 1 ]; then
+              echo "Tox failed with exit code 1 (attempt $attempt). Attempting to commit changes..."
+              git add .
+              git commit -m "chore: commit changes for release"
+            else
+              echo "Tox failed with exit code $exit_code (attempt $attempt). Not retrying."
+              break
+            fi
+
+            attempt=$(( attempt + 1 ))
+            echo "Retrying in 10 seconds..."
+            sleep 10
+          done
+          if [ $attempt -ge $max_attempts ]; then
+            echo "Tox failed after $attempt attempts. Exiting..."
+            exit 1
+          fi
